# Generated by Django 3.2.4 on 2021-08-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='images_content',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='update')),
                ('images', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='image')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='food.content')),
            ],
            options={
                'verbose_name_plural': 'image',
                'db_table': 'tb_image',
            },
        ),
    ]
